/** biome-ignore-all lint/suspicious/noTemplateCurlyInString: ... */
import type { CompilationPlan, GeneratedModule } from "@/types";
import { relativeModuleSpecifier } from "@/utils/path";

export const generateErrorModule = (plan: CompilationPlan): GeneratedModule => {
  const moduleId = `${plan.outputRoot}/error.ts`;
  const typesModuleId = `${plan.outputRoot}/types.ts`;

  const code = [
    `import { HTTPException } from "hono/http-exception";`,
    `import type { ErrorHandler } from "hono";`,
    `import type { App } from ${JSON.stringify(
      relativeModuleSpecifier(moduleId, typesModuleId)
    )};`,
    `import type { NoohStandardSchema } from "@nooh-ts/nooh";`,
    "",
    "const isRecord = (",
    "  value: unknown,",
    "): value is Record<PropertyKey, unknown> =>",
    '  typeof value === "object" && value !== null;',
    "",
    "export class ResponseValidationError extends Error {",
    "  readonly route: string;",
    "  readonly issues: readonly unknown[];",
    "",
    "  constructor(",
    "    route: string,",
    "    issues: readonly unknown[],",
    "  ) {",
    "    super(`Response validation failed for ${route}.`);",
    '    this.name = "ResponseValidationError";',
    "    this.route = route;",
    "    this.issues = issues;",
    "  }",
    "}",
    "",
    "const extractResponseValue = async (",
    "  response: Response,",
    "  route: string,",
    "): Promise<unknown> => {",
    "  if (",
    "    response.status === 204 ||",
    "    response.status === 205 ||",
    "    response.status === 304 ||",
    "    response.body === null",
    "  ) {",
    "    return undefined;",
    "  }",
    "",
    "  const contentType =",
    '    response.headers.get("content-type")?.split(";", 1)[0]?.trim().toLowerCase() ??',
    '    "";',
    "",
    "  let clone: Response;",
    "",
    "  try {",
    "    clone = response.clone();",
    "  } catch {",
    "    throw new ResponseValidationError(route, [",
    "      {",
    '        message: "The response body could not be cloned for validation.",',
    "      },",
    "    ]);",
    "  }",
    "",
    "  if (",
    '    contentType === "application/json" ||',
    '    contentType.endsWith("+json")',
    "  ) {",
    "    try {",
    "      return await clone.json();",
    "    } catch {",
    "      throw new ResponseValidationError(route, [",
    "        {",
    '          message: "The response body is not valid JSON.",',
    "        },",
    "      ]);",
    "    }",
    "  }",
    "",
    '  if (contentType.startsWith("text/")) {',
    "    return clone.text();",
    "  }",
    "",
    "  throw new ResponseValidationError(route, [",
    "    {",
    "      message:",
    "        `Response validation only supports JSON and text responses. ` +",
    '        `Received "${contentType || "unknown"}".`,',
    "    },",
    "  ]);",
    "};",
    "",
    "export const validateResponse = async (",
    "  response: Response,",
    "  schema: NoohStandardSchema,",
    "  route: string,",
    "): Promise<Response> => {",
    "  const value = await extractResponseValue(response, route);",
    "",
    '  const validate = schema["~standard"]',
    "    .validate as (value: unknown) =>",
    "    | unknown",
    "    | Promise<unknown>;",
    "",
    "  const result = await validate(value);",
    "",
    "  if (",
    "    isRecord(result) &&",
    '    "issues" in result &&',
    "    Array.isArray(result.issues)",
    "  ) {",
    "    throw new ResponseValidationError(route, result.issues);",
    "  }",
    "",
    "  return response;",
    "};",
    "",
    "export const defaultErrorHandler: ErrorHandler<App> = (error, c) => {",
    "  if (error instanceof HTTPException) {",
    "    return error.getResponse();",
    "  }",
    "",
    "  console.error(error);",
    "",
    '  return c.json({ error: "Internal Server Error" }, 500);',
    "};",
    "",
  ].join("\n");

  return {
    code,
    id: moduleId,
    kind: "error",
  };
};
